package ulti;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */


import java.io.UnsupportedEncodingException;
import java.sql.Date;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.mail.internet.MimeUtility;

/**
 *
 * @author Admin
 */
public class sendEmailReject {
    public boolean sendMailReject(String email, String nametour, Date ngaydi, String messageEmail) throws UnsupportedEncodingException {
        final String username = "vntraveltouring@gmail.com";
        final String password = "tsbe wzlc rold wikt";

        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true");
        prop.put("mail.smtp.socketFactory.port", "587");
        prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");

        prop.put("mail.mime.charset", "UTF-8");
        prop.put("mail.mime.encodefilename", "true");

        Session session = Session.getInstance(prop,
                new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

//            if (messageEmail != null) {
            String emailContent = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                    + "<html dir=\"ltr\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                    + "\n"
                    + "    <head>\n"
                    + "        <meta charset=\"UTF-8\">\n"
                    + "            <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\n"
                    + "                <meta name=\"x-apple-disable-message-reformatting\">\n"
                    + "                    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                    + "                        <meta content=\"telephone=no\" name=\"format-detection\">\n"
                    + "                            <title></title>\n"
                    + "                            <style>\n"
                    + "                                #outlook a {\n"
                    + "                                    padding: 0;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .ExternalClass {\n"
                    + "                                    width: 100%;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .ExternalClass,\n"
                    + "                                .ExternalClass p,\n"
                    + "                                .ExternalClass span,\n"
                    + "                                .ExternalClass font,\n"
                    + "                                .ExternalClass td,\n"
                    + "                                .ExternalClass div {\n"
                    + "                                    line-height: 100%;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-button {\n"
                    + "                                    mso-style-priority: 100 !important;\n"
                    + "                                    text-decoration: none !important;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                a[x-apple-data-detectors] {\n"
                    + "                                    color: inherit !important;\n"
                    + "                                    text-decoration: none !important;\n"
                    + "                                    font-size: inherit !important;\n"
                    + "                                    font-family: inherit !important;\n"
                    + "                                    font-weight: inherit !important;\n"
                    + "                                    line-height: inherit !important;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-desk-hidden {\n"
                    + "                                    display: none;\n"
                    + "                                    float: left;\n"
                    + "                                    overflow: hidden;\n"
                    + "                                    width: 0;\n"
                    + "                                    max-height: 0;\n"
                    + "                                    line-height: 0;\n"
                    + "                                    mso-hide: all;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                /*\n"
                    + "                                                                                END OF IMPORTANT\n"
                    + "                                */\n"
                    + "                                s {\n"
                    + "                                    text-decoration: line-through;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                body {\n"
                    + "                                    width: 100%;\n"
                    + "                                    font-family: 'arial', 'helvetica neue', 'helvetica', 'sans-serif';\n"
                    + "                                    -webkit-text-size-adjust: 100%;\n"
                    + "                                    -ms-text-size-adjust: 100%;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                table {\n"
                    + "                                    mso-table-lspace: 0pt;\n"
                    + "                                    mso-table-rspace: 0pt;\n"
                    + "                                    border-collapse: collapse;\n"
                    + "                                    border-spacing: 0px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                table td,\n"
                    + "                                html,\n"
                    + "                                body,\n"
                    + "                                .es-wrapper {\n"
                    + "                                    padding: 0;\n"
                    + "                                    Margin: 0;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-content,\n"
                    + "                                .es-header,\n"
                    + "                                .es-footer {\n"
                    + "                                    table-layout: fixed !important;\n"
                    + "                                    width: 100%;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                img {\n"
                    + "                                    display: block;\n"
                    + "                                    border: 0;\n"
                    + "                                    outline: none;\n"
                    + "                                    text-decoration: none;\n"
                    + "                                    -ms-interpolation-mode: bicubic;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                table tr {\n"
                    + "                                    border-collapse: collapse;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                p,\n"
                    + "                                hr {\n"
                    + "                                    Margin: 0;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                h1,\n"
                    + "                                h2,\n"
                    + "                                h3,\n"
                    + "                                h4,\n"
                    + "                                h5 {\n"
                    + "                                    Margin: 0;\n"
                    + "                                    line-height: 120%;\n"
                    + "                                    mso-line-height-rule: exactly;\n"
                    + "                                    font-family: 'arial', 'helvetica neue', 'helvetica', 'sans-serif';\n"
                    + "                                }\n"
                    + "\n"
                    + "                                p,\n"
                    + "                                ul li,\n"
                    + "                                ol li,\n"
                    + "                                a {\n"
                    + "                                    -webkit-text-size-adjust: none;\n"
                    + "                                    -ms-text-size-adjust: none;\n"
                    + "                                    mso-line-height-rule: exactly;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-left {\n"
                    + "                                    float: left;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-right {\n"
                    + "                                    float: right;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p5 {\n"
                    + "                                    padding: 5px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p5t {\n"
                    + "                                    padding-top: 5px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p5b {\n"
                    + "                                    padding-bottom: 5px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p5l {\n"
                    + "                                    padding-left: 5px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p5r {\n"
                    + "                                    padding-right: 5px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p10 {\n"
                    + "                                    padding: 10px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p10t {\n"
                    + "                                    padding-top: 10px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p10b {\n"
                    + "                                    padding-bottom: 10px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p10l {\n"
                    + "                                    padding-left: 10px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p10r {\n"
                    + "                                    padding-right: 10px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p15 {\n"
                    + "                                    padding: 15px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p15t {\n"
                    + "                                    padding-top: 15px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p15b {\n"
                    + "                                    padding-bottom: 15px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p15l {\n"
                    + "                                    padding-left: 15px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p15r {\n"
                    + "                                    padding-right: 15px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p20 {\n"
                    + "                                    padding: 20px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p20t {\n"
                    + "                                    padding-top: 20px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p20b {\n"
                    + "                                    padding-bottom: 20px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p20l {\n"
                    + "                                    padding-left: 20px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p20r {\n"
                    + "                                    padding-right: 20px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p25 {\n"
                    + "                                    padding: 25px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p25t {\n"
                    + "                                    padding-top: 25px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p25b {\n"
                    + "                                    padding-bottom: 25px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p25l {\n"
                    + "                                    padding-left: 25px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p25r {\n"
                    + "                                    padding-right: 25px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p30 {\n"
                    + "                                    padding: 30px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p30t {\n"
                    + "                                    padding-top: 30px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p30b {\n"
                    + "                                    padding-bottom: 30px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p30l {\n"
                    + "                                    padding-left: 30px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p30r {\n"
                    + "                                    padding-right: 30px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p35 {\n"
                    + "                                    padding: 35px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p35t {\n"
                    + "                                    padding-top: 35px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p35b {\n"
                    + "                                    padding-bottom: 35px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p35l {\n"
                    + "                                    padding-left: 35px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p35r {\n"
                    + "                                    padding-right: 35px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p40 {\n"
                    + "                                    padding: 40px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p40t {\n"
                    + "                                    padding-top: 40px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p40b {\n"
                    + "                                    padding-bottom: 40px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p40l {\n"
                    + "                                    padding-left: 40px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-p40r {\n"
                    + "                                    padding-right: 40px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-menu td {\n"
                    + "                                    border: 0;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-menu td a img {\n"
                    + "                                    display: inline-block !important;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                /*\n"
                    + "                                                                                END CONFIG STYLES\n"
                    + "                                */\n"
                    + "                                a {\n"
                    + "                                    text-decoration: underline;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                p,\n"
                    + "                                ul li,\n"
                    + "                                ol li {\n"
                    + "                                    font-family: 'arial', 'helvetica neue', 'helvetica', 'sans-serif';\n"
                    + "                                    line-height: 150%;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                ul li,\n"
                    + "                                ol li {\n"
                    + "                                    Margin-bottom: 15px;\n"
                    + "                                    margin-left: 0;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-menu td a {\n"
                    + "                                    text-decoration: none;\n"
                    + "                                    display: block;\n"
                    + "                                    font-family: 'arial', 'helvetica neue', 'helvetica', 'sans-serif';\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-wrapper {\n"
                    + "                                    width: 100%;\n"
                    + "                                    height: 100%;\n"
                    + "                                    background-repeat: repeat;\n"
                    + "                                    background-position: center top;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-wrapper-color,\n"
                    + "                                .es-wrapper {\n"
                    + "                                    background-color: #f6f6f6;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-header {\n"
                    + "                                    background-color: transparent;\n"
                    + "                                    background-repeat: repeat;\n"
                    + "                                    background-position: center top;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-header-body {\n"
                    + "                                    background-color: #ffffff;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-header-body p,\n"
                    + "                                .es-header-body ul li,\n"
                    + "                                .es-header-body ol li {\n"
                    + "                                    color: #999999;\n"
                    + "                                    font-size: 14px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-header-body a {\n"
                    + "                                    color: #999999;\n"
                    + "                                    font-size: 14px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-content-body {\n"
                    + "                                    background-color: #ffffff;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-content-body p,\n"
                    + "                                .es-content-body ul li,\n"
                    + "                                .es-content-body ol li {\n"
                    + "                                    color: #333333;\n"
                    + "                                    font-size: 14px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-content-body a {\n"
                    + "                                    color: #faa41d;\n"
                    + "                                    font-size: 14px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-footer {\n"
                    + "                                    background-color: transparent;\n"
                    + "                                    background-repeat: repeat;\n"
                    + "                                    background-position: center top;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-footer-body {\n"
                    + "                                    background-color: #efefef;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-footer-body p,\n"
                    + "                                .es-footer-body ul li,\n"
                    + "                                .es-footer-body ol li {\n"
                    + "                                    color: #666666;\n"
                    + "                                    font-size: 14px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-footer-body a {\n"
                    + "                                    color: #666666;\n"
                    + "                                    font-size: 14px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-infoblock,\n"
                    + "                                .es-infoblock p,\n"
                    + "                                .es-infoblock ul li,\n"
                    + "                                .es-infoblock ol li {\n"
                    + "                                    line-height: 120%;\n"
                    + "                                    font-size: 12px;\n"
                    + "                                    color: #999999;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-infoblock a {\n"
                    + "                                    font-size: 12px;\n"
                    + "                                    color: #999999;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                h1 {\n"
                    + "                                    font-size: 30px;\n"
                    + "                                    font-style: normal;\n"
                    + "                                    font-weight: normal;\n"
                    + "                                    color: #333333;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                h2 {\n"
                    + "                                    font-size: 24px;\n"
                    + "                                    font-style: normal;\n"
                    + "                                    font-weight: normal;\n"
                    + "                                    color: #333333;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                h3 {\n"
                    + "                                    font-size: 20px;\n"
                    + "                                    font-style: normal;\n"
                    + "                                    font-weight: normal;\n"
                    + "                                    color: #333333;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-header-body h1 a,\n"
                    + "                                .es-content-body h1 a,\n"
                    + "                                .es-footer-body h1 a {\n"
                    + "                                    font-size: 30px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-header-body h2 a,\n"
                    + "                                .es-content-body h2 a,\n"
                    + "                                .es-footer-body h2 a {\n"
                    + "                                    font-size: 24px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-header-body h3 a,\n"
                    + "                                .es-content-body h3 a,\n"
                    + "                                .es-footer-body h3 a {\n"
                    + "                                    font-size: 20px;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                a.es-button,\n"
                    + "                                button.es-button {\n"
                    + "                                    display: inline-block;\n"
                    + "                                    background: #14141e;\n"
                    + "                                    border-radius: 0px;\n"
                    + "                                    font-size: 18px;\n"
                    + "                                    font-family: 'arial', 'helvetica neue', 'helvetica', 'sans-serif';\n"
                    + "                                    font-weight: normal;\n"
                    + "                                    font-style: normal;\n"
                    + "                                    line-height: 120%;\n"
                    + "                                    color: #efefef;\n"
                    + "                                    text-decoration: none;\n"
                    + "                                    width: auto;\n"
                    + "                                    text-align: center;\n"
                    + "                                    padding: 10px 20px 10px 20px;\n"
                    + "                                    mso-padding-alt: 0;\n"
                    + "                                    mso-border-alt: 10px solid #14141e;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                .es-button-border {\n"
                    + "                                    border-style: solid solid solid solid;\n"
                    + "                                    border-color: #14141e #14141e #14141e #14141e;\n"
                    + "                                    background: #2cb543;\n"
                    + "                                    border-width: 0px 0px 0px 0px;\n"
                    + "                                    display: inline-block;\n"
                    + "                                    border-radius: 0px;\n"
                    + "                                    width: auto;\n"
                    + "                                }\n"
                    + "\n"
                    + "                                /*\n"
                    + "                                                                                RESPONSIVE STYLES\n"
                    + "                                                                                Please do not delete and edit CSS styles below.\n"
                    + "                                                                                 \n"
                    + "                                                                                If you don't need responsive layout, please delete this section.\n"
                    + "                                */\n"
                    + "                                @media only screen and (max-width: 600px) {\n"
                    + "\n"
                    + "                                    p,\n"
                    + "                                    ul li,\n"
                    + "                                    ol li,\n"
                    + "                                    a {\n"
                    + "                                        line-height: 150% !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    h1,\n"
                    + "                                    h2,\n"
                    + "                                    h3,\n"
                    + "                                    h1 a,\n"
                    + "                                    h2 a,\n"
                    + "                                    h3 a {\n"
                    + "                                        line-height: 120% !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    h1 {\n"
                    + "                                        font-size: 30px !important;\n"
                    + "                                        text-align: center;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    h2 {\n"
                    + "                                        font-size: 26px !important;\n"
                    + "                                        text-align: center;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    h3 {\n"
                    + "                                        font-size: 20px !important;\n"
                    + "                                        text-align: center;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-header-body h1 a,\n"
                    + "                                    .es-content-body h1 a,\n"
                    + "                                    .es-footer-body h1 a {\n"
                    + "                                        font-size: 30px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-header-body h2 a,\n"
                    + "                                    .es-content-body h2 a,\n"
                    + "                                    .es-footer-body h2 a {\n"
                    + "                                        font-size: 26px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-header-body h3 a,\n"
                    + "                                    .es-content-body h3 a,\n"
                    + "                                    .es-footer-body h3 a {\n"
                    + "                                        font-size: 20px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-menu td a {\n"
                    + "                                        font-size: 14px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-header-body p,\n"
                    + "                                    .es-header-body ul li,\n"
                    + "                                    .es-header-body ol li,\n"
                    + "                                    .es-header-body a {\n"
                    + "                                        font-size: 14px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-content-body p,\n"
                    + "                                    .es-content-body ul li,\n"
                    + "                                    .es-content-body ol li,\n"
                    + "                                    .es-content-body a {\n"
                    + "                                        font-size: 16px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-footer-body p,\n"
                    + "                                    .es-footer-body ul li,\n"
                    + "                                    .es-footer-body ol li,\n"
                    + "                                    .es-footer-body a {\n"
                    + "                                        font-size: 14px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-infoblock p,\n"
                    + "                                    .es-infoblock ul li,\n"
                    + "                                    .es-infoblock ol li,\n"
                    + "                                    .es-infoblock a {\n"
                    + "                                        font-size: 12px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    *[class=\"gmail-fix\"] {\n"
                    + "                                        display: none !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-txt-c,\n"
                    + "                                    .es-m-txt-c h1,\n"
                    + "                                    .es-m-txt-c h2,\n"
                    + "                                    .es-m-txt-c h3 {\n"
                    + "                                        text-align: center !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-txt-r,\n"
                    + "                                    .es-m-txt-r h1,\n"
                    + "                                    .es-m-txt-r h2,\n"
                    + "                                    .es-m-txt-r h3 {\n"
                    + "                                        text-align: right !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-txt-l,\n"
                    + "                                    .es-m-txt-l h1,\n"
                    + "                                    .es-m-txt-l h2,\n"
                    + "                                    .es-m-txt-l h3 {\n"
                    + "                                        text-align: left !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-txt-r img,\n"
                    + "                                    .es-m-txt-c img,\n"
                    + "                                    .es-m-txt-l img {\n"
                    + "                                        display: inline !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-button-border {\n"
                    + "                                        display: block !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    a.es-button,\n"
                    + "                                    button.es-button {\n"
                    + "                                        font-size: 20px !important;\n"
                    + "                                        display: block !important;\n"
                    + "                                        border-left-width: 0px !important;\n"
                    + "                                        border-right-width: 0px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-btn-fw {\n"
                    + "                                        border-width: 10px 0px !important;\n"
                    + "                                        text-align: center !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-adaptive table,\n"
                    + "                                    .es-btn-fw,\n"
                    + "                                    .es-btn-fw-brdr,\n"
                    + "                                    .es-left,\n"
                    + "                                    .es-right {\n"
                    + "                                        width: 100% !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-content table,\n"
                    + "                                    .es-header table,\n"
                    + "                                    .es-footer table,\n"
                    + "                                    .es-content,\n"
                    + "                                    .es-footer,\n"
                    + "                                    .es-header {\n"
                    + "                                        width: 100% !important;\n"
                    + "                                        max-width: 600px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-adapt-td {\n"
                    + "                                        display: block !important;\n"
                    + "                                        width: 100% !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .adapt-img {\n"
                    + "                                        width: 100% !important;\n"
                    + "                                        height: auto !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-p0 {\n"
                    + "                                        padding: 0px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-p0r {\n"
                    + "                                        padding-right: 0px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-p0l {\n"
                    + "                                        padding-left: 0px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-p0t {\n"
                    + "                                        padding-top: 0px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-p0b {\n"
                    + "                                        padding-bottom: 0 !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-m-p20b {\n"
                    + "                                        padding-bottom: 20px !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-mobile-hidden,\n"
                    + "                                    .es-hidden {\n"
                    + "                                        display: none !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    tr.es-desk-hidden,\n"
                    + "                                    td.es-desk-hidden,\n"
                    + "                                    table.es-desk-hidden {\n"
                    + "                                        width: auto !important;\n"
                    + "                                        overflow: visible !important;\n"
                    + "                                        float: none !important;\n"
                    + "                                        max-height: inherit !important;\n"
                    + "                                        line-height: inherit !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    tr.es-desk-hidden {\n"
                    + "                                        display: table-row !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    table.es-desk-hidden {\n"
                    + "                                        display: table !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    td.es-desk-menu-hidden {\n"
                    + "                                        display: table-cell !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-menu td {\n"
                    + "                                        width: 1% !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    table.es-table-not-adapt,\n"
                    + "                                    .esd-block-html table {\n"
                    + "                                        width: auto !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    table.es-social {\n"
                    + "                                        display: inline-block !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    table.es-social td {\n"
                    + "                                        display: inline-block !important;\n"
                    + "                                    }\n"
                    + "\n"
                    + "                                    .es-desk-hidden {\n"
                    + "                                        display: table-row !important;\n"
                    + "                                        width: auto !important;\n"
                    + "                                        overflow: visible !important;\n"
                    + "                                        max-height: inherit !important;\n"
                    + "                                    }\n"
                    + "                                }\n"
                    + "\n"
                    + "                            </style>\n"
                    + "                            </head>\n"
                    + "\n"
                    + "                            <body>\n"
                    + "                                <div dir=\"ltr\" class=\"es-wrapper-color\">\n"
                    + "                                    <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
                    + "                                        <tbody>\n"
                    + "                                            <tr>\n"
                    + "                                                <td class=\"esd-email-paddings\" valign=\"top\">\n"
                    + "<table class=\"es-content esd-header-popover\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                            <tbody>\n"
                    + "                                <tr>\n"
                    + "                                    <td class=\"esd-stripe\" align=\"center\">\n"
                    + "                                        <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\n"
                    + "                                            <tbody>\n"
                    + "                                                <tr>\n"
                    + "                                                    <td class=\"esd-structure\" align=\"left\">\n"
                    + "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
                    + "                                                            <tbody>\n"
                    + "                                                                <tr>\n"
                    + "                                                                    <td class=\"esd-container-frame\" width=\"600\" valign=\"top\" align=\"center\">\n"
                    + "                                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
                    + "                                                                            <tbody>\n"
                    + "                                                                                <tr>\n"
                    + "                                                                                    <td class=\"esd-block-banner\" style=\"position: relative;\" align=\"center\" esdev-config=\"h40\"><a target=\"_blank\" href=\"http://localhost:9999/VNTravel/home\"><img class=\"adapt-img esdev-stretch-width esdev-banner-rendered\" src=\"https://demo.stripocdn.email/content/guids/bannerImgGuid/images/image17106885166645631.png\" alt=\"Hà N?i Tour\" title=\"Hà N?i Tour\" width=\"550\" style=\"display: block;\"></a></td>\n"
                    + "                                                                                </tr>\n"
                    + "                                                                            </tbody>\n"
                    + "                                                                        </table>\n"
                    + "                                                                    </td>\n"
                    + "                                                                </tr>\n"
                    + "                                                            </tbody>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </tbody>\n"
                    + "                                        </table>\n"
                    + "                                    </td>\n"
                    + "                                </tr>\n"
                    + "                            </tbody>\n"
                    + "                        </table>"
                    + "                                                    <table class=\"es-content es-visible-simple-html-only\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                                                        <tbody>\n"
                    + "                                                            <tr>\n"
                    + "                                                                <td class=\"esd-stripe es-stripe-html\" align=\"center\">\n"
                    + "                                                                    <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\n"
                    + "                                                                        <tbody>\n"
                    + "                                                                            <tr>\n"
                    + "                                                                                <td class=\"esd-structure es-p20t es-p20r es-p20l\" esd-general-paddings-checked=\"false\" align=\"left\">\n"
                    + "                                                                                    <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
                    + "                                                                                        <tbody>\n"
                    + "                                                                                            <tr>\n"
                    + "                                                                                                <td class=\"esd-container-frame\" width=\"560\" valign=\"top\" align=\"center\">\n"
                    + "                                                                                                    <table style=\"border-collapse: separate; border-width: 0px 0px 2px; border-style: solid; border-color: #ffffff #ffffff #faa41d;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
                    + "                                                                                                        <tbody>\n"
                    + "                                                                                                            <tr>\n"
                    + "                                                                                                                <td class=\"esd-block-text es-p5b\" align=\"center\">\n"
                    + "                                                                                                                    <h2 style=\"line-height: 120%; color: #333333;\"><span style=\"color: #faa41d; line-height: 120%;\">" + messageEmail + "</span><br></h2>\n"
                    + "                                                                                                                </td>\n"
                    + "                                                                                                            </tr>\n"
                    + "                                                                                                        </tbody>\n"
                    + "                                                                                                    </table>\n"
                    + "                                                                                                </td>\n"
                    + "                                                                                            </tr>\n"
                    + "                                                                                        </tbody>\n"
                    + "                                                                                    </table>\n"
                    + "                                                                                </td>\n"
                    + "                                                                            </tr>\n"
                    + "                                                                            <tr class=\"es-visible-simple-html-only\">\n"
                    + "                                                                                <td class=\"esd-structure es-p30t es-p30b es-p30r es-p30l es-struct-html\" esd-general-paddings-checked=\"false\" esd-custom-block-id=\"2664\" align=\"left\">\n"
                    + "                                                                                    <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\n"
                    + "                                                                                        <tbody>\n"
                    + "                                                                                            <tr>\n"
                    + "                                                                                                <td class=\"esd-container-frame\" width=\"540\" align=\"left\">\n"
                    + "                                                                                                    <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
                    + "                                                                                                        <tbody>\n"+
                                                                                                                      
                   "    <td class=\\\"esd-block-text es-p20t es-p20b es-m-txt-c\\\" align=\\\"center\\\">" +
"        <p>L?i Xin L?i v? Tour không ???c Ch?p Nh?n<br><br>" +
"        Kính g?i Quý Khách hàng yêu quý,<br><br>" +
"        Chúng tôi xin g?i l?i chào và l?i xin l?i chân thành nh?t ??n quý khách hàng.<br><br>" +
"        Chúng tôi ?ã nh?n ???c ??n ??t tour c?a quý khách hàng và xin chân thành thông báo r?ng tour này ?ã không ???c ch?p nh?n do m?t s? lý do n?m ngoài t?m ki?m soát c?a chúng tôi.<br><br>" +
"        Chúng tôi hi?u r?ng s? không ch?p nh?n c?a tour này có th? gây ra s? phi?n toái và th?t v?ng cho quý khách hàng, và chúng tôi xin ???c g?i l?i xin l?i sâu s?c t? ?áy lòng c?a chúng tôi.<br>" +
"        ?? bù ??p cho s? b?t ti?n này, chúng tôi s? hoàn tr? l?i toàn b? s? ti?n ?ã thanh toán cho tour này vào tài kho?n c?a quý khách hàng ngay l?p t?c. N?u có b?t k? th?c m?c ho?c yêu c?u ??c bi?t nào, xin vui lòng liên h? v?i b? ph?n ch?m sóc khách hàng c?a chúng tôi qua s? ?i?n tho?i [0928008008] ho?c email [vntraveltouring@gmail.com].<br>" +
"        Chúng tôi hi v?ng r?ng quý khách hàng s? thông c?m và ti?p t?c tin t??ng HaNoiTour trong nh?ng d?ch v? du l?ch s?p t?i. Chúng tôi cam k?t s? c?i thi?n d?ch v? c?a mình và t?o ra nh?ng tr?i nghi?m du l?ch t?t nh?t cho quý khách hàng.<br><br>" +
"        M?t l?n n?a, xin l?i v? s? b?t ti?n này và c?m ?n quý khách hàng ?ã luôn ?ng h? HaNoiTour.<br><br>" +
"        Trân tr?ng,<br>" +
"        [HaNoiTour]</p>" +
"    </td>" +
"</tr>\n"
                                                                                                                         
                    + "                                                                                                                    <td style=\"padding: 15px;width: 150px; background-color: #ebebeb;\" class=\"esd-block-text es-p20t es-p20b es-m-txt-c\" align=\"center\">\n"
                    + "                                                                                                                    </td>\n"
                    + "                                                                                                            </tr>\n"
                    + "                                                                                                        </tbody>\n"
                    + "                                                                                                    </table>\n"
                    + "                                                                                                </td>\n"
                    + "                                                                                            </tr>\n"
                    + "                                                                                        </tbody>\n"
                    + "                                                                                    </table>\n"
                    + "                                                                                </td>\n"
                    + "                                                                            </tr>\n"
                    + "                                                                        </tbody>\n"
                    + "                                                                    </table>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </tbody>\n"
                    + "                                                    </table>\n"
                    + "                                                    <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer esd-footer-popover\" align=\"center\">\n"
                    + "                                                        <tbody>\n"
                    + "                                                            <tr>\n"
                    + "                                                                <td class=\"esd-stripe\" esd-custom-block-id=\"2674\" align=\"center\">\n"
                    + "                                                                    <table class=\"es-footer-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                                                                        <tbody>\n"
                    + "                                                                            <tr>\n"
                    + "                                                                                <td class=\"esd-structure es-p20t es-p20r es-p20l\" align=\"left\" bgcolor=\"#040404\" style=\"background-color: #040404;\">\n"
                    + "                                                                                    <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                    + "                                                                                        <tbody>\n"
                    + "                                                                                            <tr>\n"
                    + "                                                                                                <td width=\"560\" class=\"esd-container-frame\" align=\"center\" valign=\"top\">\n"
                    + "                                                                                                    <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                    + "                                                                                                        <tbody>\n"
                    + "                                                                                                            <tr>\n"
                    + "                                                                                                                <td esdev-links-color=\"#666666\" align=\"left\" class=\"esd-block-text\" esd-links-color=\"#ffffff\" esd-links-underline=\"none\">\n"
                    + "                                                                                                                    <p style=\"line-height: 200%; color: #ffffff;\">Liên h?:</p>\n"
                    + "                                                                                                                    <p style=\"color: #ffffff;\">Email: vntraveltouring@gmail.com</p>\n"
                    + "                                                                                                                    <p style=\"color: #ffffff;\">Phone: <a target=\"_blank\" href=\"tel:123456789\" style=\"color: #ffffff; text-decoration: none;\">0</a>928008008</p>\n"
                    + "                                                                                                                    <p style=\"line-height: 200%; color: #ffffff;\">??a ch?: Khu Công Ngh? Cao Hòa L?c, Km29 ??i l? Th?ng Long, Th?ch Hoà, Th?ch Th?t, Hà N?i</p>\n"
                    + "                                                                                                                </td>\n"
                    + "                                                                                                            </tr>\n"
                    + "                                                                                                        </tbody>\n"
                    + "                                                                                                    </table>\n"
                    + "                                                                                                </td>\n"
                    + "                                                                                            </tr>\n"
                    + "                                                                                            <tr>\n"
                    + "                                                                                                <td width=\"560\" align=\"left\" class=\"esd-container-frame\">\n"
                    + "                                                                                                    <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                    + "                                                                                                        <tbody>\n"
                    + "                                                                                                            <tr>\n"
                    + "                                                                                                                <td class=\"esd-block-social es-p5t es-p5b\" align=\"left\" style=\"font-size:0\">\n"
                    + "                                                                                                                    <table class=\"es-table-not-adapt es-social\" cellspacing=\"0\" cellpadding=\"0\">\n"
                    + "                                                                                                                        <tbody>\n"
                    + "                                                                                                                            <tr>\n"
                    + "                                                                                                                                <td class=\"es-p10r\" valign=\"top\" align=\"center\"><a href><img title=\"Twitter\" src=\"https://tlr.stripocdn.email/content/assets/img/social-icons/rounded-gray/twitter-rounded-gray.png\" alt=\"Tw\" width=\"24\" height=\"24\"></a></td>\n"
                    + "                                                                                                                                <td class=\"es-p10r\" valign=\"top\" align=\"center\"><a href><img title=\"Facebook\" src=\"https://tlr.stripocdn.email/content/assets/img/social-icons/rounded-gray/facebook-rounded-gray.png\" alt=\"Fb\" width=\"24\" height=\"24\"></a></td>\n"
                    + "                                                                                                                                <td class=\"es-p10r\" valign=\"top\" align=\"center\"><a href><img title=\"Youtube\" src=\"https://tlr.stripocdn.email/content/assets/img/social-icons/rounded-gray/youtube-rounded-gray.png\" alt=\"Yt\" width=\"24\" height=\"24\"></a></td>\n"
                    + "                                                                                                                                <td valign=\"top\" align=\"center\"><a href><img title=\"Vkontakte\" src=\"https://tlr.stripocdn.email/content/assets/img/social-icons/rounded-gray/vk-rounded-gray.png\" alt=\"Vk\" width=\"24\" height=\"24\"></a></td>\n"
                    + "                                                                                                                            </tr>\n"
                    + "                                                                                                                        </tbody>\n"
                    + "                                                                                                                    </table>\n"
                    + "                                                                                                                </td>\n"
                    + "                                                                                                            </tr>\n"
                    + "                                                                                                        </tbody>\n"
                    + "                                                                                                    </table>\n"
                    + "                                                                                                </td>\n"
                    + "                                                                                            </tr>\n"
                    + "                                                                                        </tbody>\n"
                    + "                                                                                    </table>\n"
                    + "                                                                                </td>\n"
                    + "                                                                            </tr>\n"
                    + "                                                                        </tbody>\n"
                    + "                                                                    </table>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </tbody>\n"
                    + "                                                    </table>\n"
                    + "                                                </td>\n"
                    + "                                            </tr>\n"
                    + "                                        </tbody>\n"
                    + "                                    </table>\n"
                    + "                                </div>\n"
                    + "                                <div class=\"banner-toolbar\"></div>\n"
                    + "                            </body>\n"
                    + "\n"
                    + "                            </html>";
//            }

            Multipart multipart = new MimeMultipart();

            MimeBodyPart htmlPart = new MimeBodyPart();
            htmlPart.setContent(emailContent, "text/html; charset=utf-8");
            multipart.addBodyPart(htmlPart);

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(username));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(email));

            message.setSubject(MimeUtility.encodeText("Hà N?i Tour", "UTF-8", "B"));

            message.setContent(multipart);

            Transport.send(message);
            System.out.println("Done");
            return true;
        } catch (MessagingException | UnsupportedEncodingException e) {
            e.printStackTrace(); // Log the exception for troubleshooting
        }

        // Log the exception for troubleshooting
        return false;
    }

    public boolean sendMailForBuy(String email, int randomNumber, String messageEmail) throws UnsupportedEncodingException {
        final String username = "vntraveltouring@gmail.com";
        final String password = "tsbe wzlc rold wikt";

        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true");
        prop.put("mail.smtp.socketFactory.port", "587");
        prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");

        prop.put("mail.mime.charset", "UTF-8");
        prop.put("mail.mime.encodefilename", "true");

        Session session = Session.getInstance(prop,
                new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {
            String emailContent = "Hà N?i Tour\n"
                    + "\n"
                    + "Kính g?i: Quý khách\n"
                    + messageEmail + "\n"
                    + "Quý khách ?ã ??t mua thành công chuy?n tour :\n"
                    + "\t\t\t\t\t\t" + randomNumber + "\n"
                    + "Hà N?i Tour hân h?nh ???c ph?c v? Quý khách.\n"
                    + "Trân tr?ng!";

            Multipart multipart = new MimeMultipart();
            MimeBodyPart textPart = new MimeBodyPart();
            textPart.setText(emailContent, "UTF-8");
            multipart.addBodyPart(textPart);

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(username));
            message.addRecipient(
                    Message.RecipientType.TO,
                    new InternetAddress(email));

            // Set the subject with proper encoding using MimeUtility.encodeText
            message.setSubject(MimeUtility.encodeText("Hà N?i Tour", "UTF-8", "B"));

            message.setContent(multipart);

            Transport.send(message);
            System.out.println("Done");
            return true;
        } catch (MessagingException | UnsupportedEncodingException e) {
            // Log the exception for troubleshooting
        }
        // Log the exception for troubleshooting
        return false;
    }
}
